#!/usr/bin/env python3
"""
Stan model generated by DoodleBUGS
Run with CmdStanPy: pip install cmdstanpy
"""
import json
import os
import cmdstanpy

model_code = """
data {
  int<lower=1> doses;
  int<lower=1> plates;
  array[doses] real x;
  array[doses, plates] int y;
}

parameters {
  real alpha;
  real beta;
  real gamma;
  real<lower=0> tau;
  array[doses, plates] real lambda;
}

transformed parameters {
  array[doses, plates] real mu;
  for (i in 1:doses) {
    for (j in 1:plates) {
      mu[i,j] = exp(alpha + beta * log(x[i] + 10) + gamma * x[i] + lambda[i, j]);
    }
  }
}

model {
  alpha ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  beta ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  gamma ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  tau ~ gamma(0.001, 0.001);
  for (i in 1:doses) {
    for (j in 1:plates) {
      lambda[i,j] ~ normal(0.0, 1.0 / sqrt(tau));
      y[i,j] ~ poisson(mu[i, j]);
    }
  }
}

generated quantities {
  real sigma;
  sigma = 1 / sqrt(tau);
}
"""

data = json.loads("""
{
  "doses": 6,
  "plates": 3,
  "y": [
    [
      15,
      21,
      29
    ],
    [
      16,
      18,
      21
    ],
    [
      16,
      26,
      33
    ],
    [
      27,
      41,
      60
    ],
    [
      33,
      38,
      41
    ],
    [
      20,
      27,
      42
    ]
  ],
  "x": [
    0,
    10,
    33,
    100,
    333,
    1000
  ]
}
""")

inits = json.loads("""
{
  "alpha": 0,
  "beta": 0,
  "gamma": 0,
  "tau": 0.1
}
""")

model_dir = os.path.join(os.path.dirname(__file__), "stan_model")
os.makedirs(model_dir, exist_ok=True)

model_file = os.path.join(model_dir, "model.stan")
with open(model_file, "w") as f:
    f.write(model_code)

data_file = os.path.join(model_dir, "data.json")
with open(data_file, "w") as f:
    json.dump(data, f)

inits_file = os.path.join(model_dir, "inits.json")
with open(inits_file, "w") as f:
    json.dump(inits, f)

model = cmdstanpy.CmdStanModel(stan_file=model_file)
fit = model.sample(
    data=data_file,
    inits=inits_file,
    chains=4,
    iter_warmup=1000,
    iter_sampling=1000,
    seed=42,
)

print(fit.summary())
print(fit.diagnose())
