#!/usr/bin/env python3
"""
Stan model generated by DoodleBUGS
Run with CmdStanPy: pip install cmdstanpy
"""
import json
import os
import cmdstanpy

model_code = """
data {
  int<lower=1> N;
  array[N] int n;
  array[N] int r;
}

parameters {
  array[N] real<lower=0, upper=1> p;
}

model {
  p ~ beta(1.0, 1.0);
  r ~ binomial(n, p);
}
"""

data = json.loads("""
{
  "n": [
    47,
    148,
    119,
    810,
    211,
    196,
    148,
    215,
    207,
    97,
    256,
    360
  ],
  "r": [
    0,
    18,
    8,
    46,
    8,
    13,
    9,
    31,
    14,
    8,
    29,
    24
  ],
  "N": 12
}
""")

inits = json.loads("""
{
  "p": [
    0.1,
    0.1,
    0.1,
    0.1,
    0.1,
    0.1,
    0.1,
    0.1,
    0.1,
    0.1,
    0.1,
    0.1
  ]
}
""")

model_dir = os.path.join(os.path.dirname(__file__), "stan_model")
os.makedirs(model_dir, exist_ok=True)

model_file = os.path.join(model_dir, "model.stan")
with open(model_file, "w") as f:
    f.write(model_code)

data_file = os.path.join(model_dir, "data.json")
with open(data_file, "w") as f:
    json.dump(data, f)

inits_file = os.path.join(model_dir, "inits.json")
with open(inits_file, "w") as f:
    json.dump(inits, f)

model = cmdstanpy.CmdStanModel(stan_file=model_file)
fit = model.sample(
    data=data_file,
    inits=inits_file,
    chains=4,
    iter_warmup=1000,
    iter_sampling=1000,
    seed=42,
)

print(fit.summary())
print(fit.diagnose())
