#!/usr/bin/env python3
"""
Stan model generated by DoodleBUGS
Run with CmdStanPy: pip install cmdstanpy
"""
import json
import os
import cmdstanpy

model_code = """
data {
  int<lower=1> N;
  int<lower=1> M;
  array[N] real sex;
  array[N] int disease;
  array[N, M] real age;
  array[N, M] real t;
  array[N, M] real t_cen;
  array[N, M] int t_is_obs;
}

parameters {
  real alpha;
  real beta_age;
  real beta_sex;
  real<lower=0> tau;
  real<lower=0> r;
  array[3] real beta_dis_free;
  array[N] real b;
}

transformed parameters {
  array[4] real beta_dis;
  beta_dis[1] = 0;  // placeholder: outside plate range
  beta_dis[2] = beta_dis_free[1];
  beta_dis[3] = beta_dis_free[2];
  beta_dis[4] = beta_dis_free[3];
  array[N, M] real mu;
  for (i in 1:N) {
    for (j in 1:M) {
      mu[i,j] = exp(alpha + beta_age * age[i, j] + beta_sex * sex[i] + beta_dis[disease[i]] + b[i]);
    }
  }
}

model {
  alpha ~ normal(0.0, 1.0 / sqrt(0.0001));
  beta_age ~ normal(0.0, 1.0 / sqrt(0.0001));
  beta_sex ~ normal(0.0, 1.0 / sqrt(0.0001));
  tau ~ gamma(1.0E-3, 1.0E-3);
  r ~ gamma(1.0, 1.0E-3);
  b ~ normal(0.0, 1.0 / sqrt(tau));
  for (i in 1:N) {
    for (j in 1:M) {
      if (t_is_obs[i,j] == 1) {
        t[i,j] ~ weibull(r, 1.0 / (mu[i, j]));
      } else {
        target += weibull_lccdf(t_cen[i, j] | r, 1.0 / (mu[i, j]));
      }
    }
  }
  for (k in 2:4) {
    beta_dis[k] ~ normal(0.0, 1.0 / sqrt(0.0001));
  }
}

generated quantities {
  real sigma;
  sigma = 1 / sqrt(tau);
}
"""

data = json.loads("""
{
  "N": 38,
  "M": 2,
  "t": [
    [
      8,
      16
    ],
    [
      23,
      13
    ],
    [
      22,
      28
    ],
    [
      447,
      318
    ],
    [
      30,
      12
    ],
    [
      24,
      245
    ],
    [
      7,
      9
    ],
    [
      511,
      30
    ],
    [
      53,
      196
    ],
    [
      15,
      154
    ],
    [
      7,
      333
    ],
    [
      141,
      8
    ],
    [
      96,
      38
    ],
    [
      149,
      70
    ],
    [
      536,
      25
    ],
    [
      17,
      4
    ],
    [
      185,
      177
    ],
    [
      292,
      114
    ],
    [
      22,
      159
    ],
    [
      15,
      108
    ],
    [
      152,
      562
    ],
    [
      402,
      24
    ],
    [
      13,
      66
    ],
    [
      39,
      46
    ],
    [
      12,
      40
    ],
    [
      113,
      201
    ],
    [
      132,
      156
    ],
    [
      34,
      30
    ],
    [
      2,
      25
    ],
    [
      130,
      26
    ],
    [
      27,
      58
    ],
    [
      5,
      43
    ],
    [
      152,
      30
    ],
    [
      190,
      5
    ],
    [
      119,
      8
    ],
    [
      54,
      16
    ],
    [
      6,
      78
    ],
    [
      63,
      8
    ]
  ],
  "t_cen": [
    [
      0,
      0
    ],
    [
      0,
      13
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      8
    ],
    [
      0,
      0
    ],
    [
      149,
      70
    ],
    [
      0,
      25
    ],
    [
      0,
      4
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      22,
      159
    ],
    [
      0,
      108
    ],
    [
      0,
      0
    ],
    [
      0,
      24
    ],
    [
      0,
      0
    ],
    [
      0,
      46
    ],
    [
      0,
      0
    ],
    [
      113,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      0
    ],
    [
      5,
      0
    ],
    [
      0,
      0
    ],
    [
      0,
      5
    ],
    [
      0,
      0
    ],
    [
      54,
      16
    ],
    [
      6,
      0
    ],
    [
      0,
      8
    ]
  ],
  "sex": [
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0
  ],
  "disease": [
    1,
    2,
    1,
    1,
    1,
    1,
    2,
    2,
    3,
    2,
    3,
    1,
    3,
    3,
    1,
    3,
    1,
    1,
    2,
    1,
    4,
    1,
    3,
    3,
    3,
    3,
    2,
    3,
    2,
    2,
    3,
    3,
    4,
    2,
    1,
    1,
    4,
    4
  ],
  "age": [
    [
      28,
      28
    ],
    [
      48,
      48
    ],
    [
      32,
      32
    ],
    [
      31,
      32
    ],
    [
      10,
      10
    ],
    [
      16,
      17
    ],
    [
      51,
      51
    ],
    [
      55,
      56
    ],
    [
      69,
      69
    ],
    [
      51,
      52
    ],
    [
      44,
      44
    ],
    [
      34,
      34
    ],
    [
      35,
      35
    ],
    [
      42,
      42
    ],
    [
      17,
      17
    ],
    [
      60,
      60
    ],
    [
      60,
      60
    ],
    [
      43,
      44
    ],
    [
      53,
      53
    ],
    [
      44,
      44
    ],
    [
      46,
      47
    ],
    [
      30,
      30
    ],
    [
      62,
      63
    ],
    [
      42,
      43
    ],
    [
      43,
      43
    ],
    [
      57,
      58
    ],
    [
      10,
      10
    ],
    [
      52,
      52
    ],
    [
      53,
      53
    ],
    [
      54,
      54
    ],
    [
      56,
      56
    ],
    [
      50,
      51
    ],
    [
      57,
      57
    ],
    [
      44,
      45
    ],
    [
      22,
      22
    ],
    [
      42,
      42
    ],
    [
      52,
      52
    ],
    [
      60,
      60
    ]
  ],
  "beta_dis": [
    0,
    0,
    0,
    0
  ],
  "t_is_obs": [
    [
      1,
      1
    ],
    [
      1,
      0
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      0
    ],
    [
      1,
      1
    ],
    [
      0,
      0
    ],
    [
      1,
      0
    ],
    [
      1,
      0
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      0,
      0
    ],
    [
      1,
      0
    ],
    [
      1,
      1
    ],
    [
      1,
      0
    ],
    [
      1,
      1
    ],
    [
      1,
      0
    ],
    [
      1,
      1
    ],
    [
      0,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      1
    ],
    [
      0,
      1
    ],
    [
      1,
      1
    ],
    [
      1,
      0
    ],
    [
      1,
      1
    ],
    [
      0,
      0
    ],
    [
      0,
      1
    ],
    [
      1,
      0
    ]
  ]
}
""")

inits = json.loads("""
{
  "beta_age": 0,
  "beta_sex": 0,
  "alpha": 0,
  "r": 1,
  "tau": 0.3,
  "beta_dis_free": [
    0,
    0,
    0
  ]
}
""")

model_dir = os.path.join(os.path.dirname(__file__), "stan_model")
os.makedirs(model_dir, exist_ok=True)

model_file = os.path.join(model_dir, "model.stan")
with open(model_file, "w") as f:
    f.write(model_code)

data_file = os.path.join(model_dir, "data.json")
with open(data_file, "w") as f:
    json.dump(data, f)

inits_file = os.path.join(model_dir, "inits.json")
with open(inits_file, "w") as f:
    json.dump(inits, f)

model = cmdstanpy.CmdStanModel(stan_file=model_file)
fit = model.sample(
    data=data_file,
    inits=inits_file,
    chains=4,
    iter_warmup=1000,
    iter_sampling=1000,
    seed=42,
)

print(fit.summary())
print(fit.diagnose())
