#!/usr/bin/env python3
"""
Stan model generated by DoodleBUGS
Run with CmdStanPy: pip install cmdstanpy
"""
import json
import os
import cmdstanpy

model_code = """
data {
  int<lower=1> P;
  int<lower=1> N;
  array[P] real sign;
  array[N] real group;
  array[N, P] real Y;
}

transformed data {
  array[N, P] int T;
  for (k in 1:P) {
    for (i in 1:N) {
      T[i,k] = to_int(round(group[i] * (k - 1.5) + 1.5));
    }
  }
}

parameters {
  real mu;
  real phi;
  real pi;
  real<lower=0> tau1;
  real<lower=0> tau2;
  array[N] real delta;
}

transformed parameters {
  array[N, P] real m;
  for (k in 1:P) {
    for (i in 1:N) {
      m[i,k] = mu + sign[T[i, k]] * phi / 2 + sign[k] * pi / 2 + delta[i];
    }
  }
}

model {
  mu ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  phi ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  pi ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  tau1 ~ gamma(0.001, 0.001);
  tau2 ~ gamma(0.001, 0.001);
  for (k in 1:P) {
    for (i in 1:N) {
      Y[i,k] ~ normal(m[i, k], 1.0 / sqrt(tau1));
    }
  }
  delta ~ normal(0.0, 1.0 / sqrt(tau2));
}

generated quantities {
  real theta;
  real sigma1;
  real sigma2;
  real equiv;
  theta = exp(phi);
  sigma1 = 1 / sqrt(tau1);
  sigma2 = 1 / sqrt(tau2);
  equiv = (theta - 0.8 >= 0 ? 1 : 0) - (theta - 1.2 >= 0 ? 1 : 0);
}
"""

data = json.loads("""
{
  "N": 10,
  "P": 2,
  "group": [
    1,
    1,
    -1,
    -1,
    -1,
    1,
    1,
    1,
    -1,
    -1
  ],
  "Y": [
    [
      1.4,
      1.65
    ],
    [
      1.64,
      1.57
    ],
    [
      1.44,
      1.58
    ],
    [
      1.36,
      1.68
    ],
    [
      1.65,
      1.69
    ],
    [
      1.08,
      1.31
    ],
    [
      1.09,
      1.43
    ],
    [
      1.25,
      1.44
    ],
    [
      1.25,
      1.39
    ],
    [
      1.3,
      1.52
    ]
  ],
  "sign": [
    1,
    -1
  ]
}
""")

inits = json.loads("""
{
  "mu": 0,
  "phi": 0,
  "pi": 0,
  "tau1": 1,
  "tau2": 1
}
""")

model_dir = os.path.join(os.path.dirname(__file__), "stan_model")
os.makedirs(model_dir, exist_ok=True)

model_file = os.path.join(model_dir, "model.stan")
with open(model_file, "w") as f:
    f.write(model_code)

data_file = os.path.join(model_dir, "data.json")
with open(data_file, "w") as f:
    json.dump(data, f)

inits_file = os.path.join(model_dir, "inits.json")
with open(inits_file, "w") as f:
    json.dump(inits, f)

model = cmdstanpy.CmdStanModel(stan_file=model_file)
fit = model.sample(
    data=data_file,
    inits=inits_file,
    chains=4,
    iter_warmup=1000,
    iter_sampling=1000,
    seed=42,
)

print(fit.summary())
print(fit.diagnose())
