#!/usr/bin/env python3
"""
Stan model generated by DoodleBUGS
Run with CmdStanPy: pip install cmdstanpy
"""
import json
import os
import cmdstanpy

model_code = """
data {
  int<lower=1> M;
  int<lower=1> N;
  array[M, N] real t;
  array[M, N] real t_cen;
  array[M, N] int t_is_obs;
}

parameters {
  real<lower=0.1, upper=10> r;
  array[M] real beta;
}

transformed parameters {
  array[M] real mu;
  for (i in 1:M) {
    mu[i] = exp(beta[i]);
  }
}

model {
  r ~ uniform(0.1, 10);
  beta ~ normal(0.0, 1.0 / sqrt(0.001));
  for (i in 1:M) {
    for (j in 1:N) {
      if (t_is_obs[i,j] == 1) {
        t[i,j] ~ weibull(r, 1.0 / (mu[i]));
      } else {
        target += weibull_lccdf(t_cen[i, j] | r, 1.0 / (mu[i]));
      }
    }
  }
}

generated quantities {
  array[M] real median;
  real veh_control;
  real test_sub;
  real pos_control;
  for (i in 1:M) {
    median[i] = pow(log(2) * exp(-beta[i]), 1 / r);
  }
  veh_control = beta[2] - beta[1];
  test_sub = beta[3] - beta[1];
  pos_control = beta[4] - beta[1];
}
"""

data = json.loads("""
{
  "M": 4,
  "N": 20,
  "t": [
    [
      12,
      1,
      21,
      25,
      11,
      26,
      27,
      30,
      13,
      12,
      21,
      20,
      23,
      25,
      23,
      29,
      35,
      40,
      31,
      36
    ],
    [
      32,
      27,
      23,
      12,
      18,
      40,
      40,
      38,
      29,
      30,
      40,
      32,
      40,
      40,
      40,
      40,
      25,
      30,
      37,
      27
    ],
    [
      22,
      26,
      10,
      28,
      19,
      15,
      12,
      35,
      35,
      10,
      22,
      18,
      24,
      12,
      40,
      40,
      31,
      24,
      37,
      29
    ],
    [
      27,
      18,
      22,
      13,
      18,
      29,
      28,
      20,
      16,
      22,
      26,
      19,
      29,
      10,
      17,
      28,
      26,
      12,
      17,
      26
    ]
  ],
  "t_cen": [
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      40,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0,
      40,
      40,
      0,
      0,
      0,
      40,
      0,
      40,
      40,
      40,
      40,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      10,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      24,
      0,
      40,
      40,
      0,
      0,
      0,
      0
    ],
    [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      20,
      0,
      0,
      0,
      0,
      29,
      10,
      0,
      0,
      0,
      0,
      0,
      0
    ]
  ],
  "t_is_obs": [
    [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      1
    ],
    [
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      1,
      1,
      0,
      1,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1
    ],
    [
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      0,
      0,
      1,
      1,
      1,
      1
    ],
    [
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1
    ]
  ]
}
""")

inits = json.loads("""
{
  "beta": [
    -1,
    -1,
    -1,
    -1
  ],
  "r": 1
}
""")

model_dir = os.path.join(os.path.dirname(__file__), "stan_model")
os.makedirs(model_dir, exist_ok=True)

model_file = os.path.join(model_dir, "model.stan")
with open(model_file, "w") as f:
    f.write(model_code)

data_file = os.path.join(model_dir, "data.json")
with open(data_file, "w") as f:
    json.dump(data, f)

inits_file = os.path.join(model_dir, "inits.json")
with open(inits_file, "w") as f:
    json.dump(inits, f)

model = cmdstanpy.CmdStanModel(stan_file=model_file)
fit = model.sample(
    data=data_file,
    inits=inits_file,
    chains=4,
    iter_warmup=1000,
    iter_sampling=1000,
    seed=42,
)

print(fit.summary())
print(fit.diagnose())
