import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";
import { serializeSpecToml } from "@mcmcjs/core";
import {
  buildTopologicalOrder,
  type GraphEdge,
  type GraphNode,
  generateBugsModel,
  getElements,
  parseModelData,
  parseUnifiedModel,
} from "@mcmcjs/doodlebugs";
import type { Command } from "commander";

const DEFAULT_SEED = 1;

/** Wrap generated BUGS model code as an idiomatic JuliaBUGS model file (the mcmc build_model contract). */
export function juliaBugsModelFile(modelCode: string): string {
  return [
    "import JuliaBUGS",
    "",
    "# Generated by `mcmc convert` from a DoodleBUGS graph.",
    'const model_def = JuliaBUGS.@bugs("""',
    modelCode,
    '""", true, false)',
    "",
    "build_model(data) = JuliaBUGS.compile(model_def, data; adtype = JuliaBUGS.ADTypes.AutoForwardDiff())",
    "",
  ].join("\n");
}

/** Build a minimal, fit-able juliabugs spec object referencing the generated model file. */
export function buildSpec(
  modelFileName: string,
  data: Record<string, unknown>,
  seed: number,
): Record<string, unknown> {
  return {
    schema_version: "0",
    seed,
    backend: { id: "juliabugs" },
    model: { kind: "file", path: `./${modelFileName}`, entry: "build_model" },
    sampler: { algorithm: "NUTS", draws: 1000, warmup: 1000, chains: 4 },
    data,
  };
}

export interface ConvertResult {
  name: string;
  modelPath: string;
  specPath: string;
}

/** Read a DoodleBUGS graph and write a JuliaBUGS model file plus a fit-able spec. */
export function convertGraph(
  graphPath: string,
  out: string | undefined,
  seed: number,
): ConvertResult {
  const model = parseUnifiedModel(readFileSync(resolve(graphPath), "utf8"));
  const elements = getElements(model);
  const nodes = elements.filter((el): el is GraphNode => el.type === "node");
  const edges = elements.filter((el): el is GraphEdge => el.type === "edge");

  // A BUGS model is a DAG; a cycle would silently mis-generate, so reject it.
  if (buildTopologicalOrder(nodes, edges).length < nodes.length) {
    throw new Error("graph has a cycle; a BUGS model must be a directed acyclic graph");
  }

  const modelCode = generateBugsModel(elements);
  const { data } = parseModelData(model);

  const prefix = out ?? graphPath.replace(/\.json$/i, "");
  const modelFileName = `${basename(prefix)}.jl`;
  const modelPath = resolve(`${prefix}.jl`);
  const specPath = resolve(`${prefix}.toml`);

  mkdirSync(dirname(modelPath), { recursive: true });
  writeFileSync(modelPath, juliaBugsModelFile(modelCode));
  writeFileSync(specPath, serializeSpecToml(buildSpec(modelFileName, data, seed)));

  return { name: model.name, modelPath, specPath };
}

function parseSeed(value: string): number {
  const n = Number.parseInt(value, 10);
  if (!Number.isInteger(n)) throw new Error(`expected an integer seed, got "${value}"`);
  return n;
}

export function registerConvert(program: Command): void {
  program
    .command("convert")
    .argument("<graph>", "DoodleBUGS graph file (.json)")
    .description("Convert a DoodleBUGS graph into a JuliaBUGS model file and a fit-able spec")
    .option("-o, --out <prefix>", "output path prefix (default: the graph file without .json)")
    .option("--seed <n>", "seed to write into the spec", parseSeed, DEFAULT_SEED)
    .option("--json", "print the result as JSON")
    .action((graphPath: string, opts: { out?: string; seed: number; json?: boolean }) => {
      const result = convertGraph(graphPath, opts.out, opts.seed);
      if (opts.json) {
        process.stdout.write(`${JSON.stringify({ ok: true, ...result }, null, 2)}\n`);
      } else {
        process.stdout.write(
          `wrote ${result.modelPath}\nwrote ${result.specPath}\n\nfit it with: mcmc fit ${result.specPath}\n`,
        );
      }
      process.exitCode = 0;
    });
}
