import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";
import { type CanonicalData, missingVariables, serializeSpecToml } from "@mcmcjs/core";
import {
  buildTopologicalOrder,
  discreteLatentNames,
  type GraphEdge,
  type GraphNode,
  generateBugsModel,
  getElements,
  parseModelData,
  parseUnifiedModel,
} from "@mcmcjs/doodleppl";
import {
  extractCensoredFields,
  generateStanDataJson,
  generateStanModel,
} from "@mcmcjs/doodleppl/stan";
import type { Command } from "commander";

const DEFAULT_SEED = 1;

/**
 * Wrap generated BUGS model code as an idiomatic JuliaBUGS model file (the mcmc
 * build_model contract). With `marginalize`, the model switches to
 * UseAutoMarginalization so NUTS never sees the discrete latents; without it,
 * gradient-based sampling of an integer state fails. `Base.invokelatest` is
 * required because JuliaBUGS evaluates node functions it defined during
 * `compile`, which this frame cannot call directly.
 */
export function juliaBugsModelFile(modelCode: string, marginalize = false): string {
  const adtype = "JuliaBUGS.ADTypes.AutoForwardDiff()";
  const build = marginalize
    ? [
        "function build_model(data)",
        "    model = JuliaBUGS.compile(model_def, data)",
        "    model = JuliaBUGS.settrans(model, true)",
        "    model = Base.invokelatest(",
        "        JuliaBUGS.set_evaluation_mode, model, JuliaBUGS.UseAutoMarginalization(),",
        "    )",
        `    return Base.invokelatest(JuliaBUGS.BUGSModelWithGradient, model, ${adtype})`,
        "end",
      ]
    : [`build_model(data) = JuliaBUGS.compile(model_def, data; adtype = ${adtype})`];

  return [
    "import JuliaBUGS",
    "",
    "# Generated by `mcmc convert` from a DoodleBUGS graph.",
    'const model_def = JuliaBUGS.@bugs("""',
    modelCode,
    '""", true, false)',
    "",
    ...(marginalize
      ? [
          "# Discrete latents are summed out exactly, so NUTS samples only the continuous",
          "# parameters; the latents come back in the chain, drawn from p(z | theta, y).",
        ]
      : []),
    ...build,
    "",
  ].join("\n");
}

/**
 * BUGS allows a period in a variable name. The generated model file passes
 * `replace_period = true` to `@bugs`, which rewrites `t.cen` to `t_cen`, so the
 * data keys have to follow or the model reads a variable the data never defines.
 */
export function underscoreDottedNames(data: Record<string, unknown>): Record<string, unknown> {
  const renamed: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(data)) {
    const name = key.replace(/\./g, "_");
    if (name in renamed) {
      throw new Error(`data has both ${key} and another name that becomes ${name} in Julia`);
    }
    renamed[name] = value;
  }
  return renamed;
}

export interface SamplerSettings {
  draws: number;
  warmup: number;
  chains: number;
}

const DEFAULT_SAMPLER: SamplerSettings = { draws: 1000, warmup: 1000, chains: 4 };

/** Build a minimal, fit-able juliabugs spec object referencing the generated model file. */
export function buildSpec(
  modelFileName: string,
  data: Record<string, unknown>,
  seed: number,
  sampler: SamplerSettings = DEFAULT_SAMPLER,
): Record<string, unknown> {
  return {
    schema_version: "0",
    seed,
    backend: { id: "juliabugs" },
    model: { kind: "file", path: `./${modelFileName}`, entry: "build_model" },
    sampler: { algorithm: "NUTS", ...sampler },
    data,
  };
}

/** Build a minimal, fit-able stan spec object referencing the generated Stan program. */
export function buildStanSpec(
  modelFileName: string,
  data: Record<string, unknown>,
  seed: number,
  sampler: SamplerSettings = DEFAULT_SAMPLER,
): Record<string, unknown> {
  return {
    schema_version: "0",
    seed,
    backend: { id: "stan" },
    model: { kind: "file", path: `./${modelFileName}` },
    sampler: { algorithm: "NUTS", ...sampler },
    data,
  };
}

export interface ConvertResult {
  name: string;
  modelPath: string;
  specPath: string;
  /** Where the data went, when an unobserved entry kept it out of the spec. */
  dataPath?: string;
}

/** Read a DoodleBUGS graph and write a JuliaBUGS model file plus a fit-able spec. */
export function convertGraph(
  graphPath: string,
  out: string | undefined,
  seed: number,
  sampler?: SamplerSettings,
  target: "juliabugs" | "stan" = "juliabugs",
): ConvertResult {
  const model = parseUnifiedModel(readFileSync(resolve(graphPath), "utf8"));
  const elements = getElements(model);
  const nodes = elements.filter((el): el is GraphNode => el.type === "node");
  const edges = elements.filter((el): el is GraphEdge => el.type === "edge");

  // A BUGS model is a DAG; a cycle would silently mis-generate, so reject it.
  if (buildTopologicalOrder(nodes, edges).length < nodes.length) {
    throw new Error("graph has a cycle; a BUGS model must be a directed acyclic graph");
  }

  const { data } = parseModelData(model);

  const prefix = out ?? graphPath.replace(/\.json$/i, "");
  const ext = target === "stan" ? "stan" : "jl";
  const modelFileName = `${basename(prefix)}.${ext}`;
  const modelPath = resolve(`${prefix}.${ext}`);
  const specPath = resolve(`${prefix}.toml`);

  let modelFile: string;
  let spec: Record<string, unknown>;
  if (target === "stan") {
    modelFile = generateStanModel(elements);
    // Stan data uses converted names, null fills, and censoring indicators.
    const stanData = JSON.parse(
      generateStanDataJson(data, extractCensoredFields(elements)),
    ) as Record<string, unknown>;
    spec = buildStanSpec(modelFileName, stanData, seed, sampler);
  } else {
    const marginalize = discreteLatentNames(elements).length > 0;
    modelFile = juliaBugsModelFile(generateBugsModel(elements), marginalize);
    spec = buildSpec(modelFileName, underscoreDottedNames(data), seed, sampler);
  }

  // A censored or partly observed outcome carries an unobserved entry, which
  // TOML has no null to write; `data_file` is how a spec points at data anyway,
  // so it goes to a JSON sidecar and the spec stays TOML.
  const specData = spec.data as CanonicalData;
  const dataPath =
    missingVariables(specData).length > 0 ? resolve(`${prefix}.data.json`) : undefined;
  if (dataPath) {
    delete spec.data;
    spec.data_file = `./${basename(dataPath)}`;
  }

  mkdirSync(dirname(modelPath), { recursive: true });
  writeFileSync(modelPath, modelFile);
  writeFileSync(specPath, serializeSpecToml(spec));
  if (dataPath) writeFileSync(dataPath, `${JSON.stringify(specData, null, 2)}\n`);

  return { name: model.name, modelPath, specPath, dataPath };
}

function parseSeed(value: string): number {
  const n = Number.parseInt(value, 10);
  if (!Number.isInteger(n)) throw new Error(`expected an integer seed, got "${value}"`);
  return n;
}

export function registerConvert(program: Command): void {
  program
    .command("convert")
    .summary("DoodleBUGS graph -> model file + spec")
    .helpGroup("Start a project:")
    .argument("<graph>", "DoodleBUGS graph file (.json)")
    .description(
      "Convert a DoodleBUGS graph into a JuliaBUGS model file (or a Stan program with --stan) and a fit-able spec",
    )
    .option("-o, --out <prefix>", "output path prefix (default: the graph file without .json)")
    .option("--stan", "emit a Stan program and a stan-backend spec instead of JuliaBUGS")
    .option("--seed <n>", "seed to write into the spec", parseSeed, DEFAULT_SEED)
    .option("--json", "print the result as JSON")
    .action(
      (graphPath: string, opts: { out?: string; seed: number; json?: boolean; stan?: boolean }) => {
        const result = convertGraph(
          graphPath,
          opts.out,
          opts.seed,
          undefined,
          opts.stan ? "stan" : "juliabugs",
        );
        if (opts.json) {
          process.stdout.write(`${JSON.stringify({ ok: true, ...result }, null, 2)}\n`);
        } else {
          const wrote = [result.modelPath, result.specPath, result.dataPath]
            .filter((path) => path !== undefined)
            .map((path) => `wrote ${path}\n`)
            .join("");
          process.stdout.write(`${wrote}\nfit it with: mcmc fit ${result.specPath}\n`);
        }
        process.exitCode = 0;
      },
    );
}
