#!/usr/bin/env python3
"""
Stan model generated by DoodleBUGS
Run with CmdStanPy: pip install cmdstanpy
"""
import json
import os
import cmdstanpy

model_code = """
data {
  int<lower=1> batches;
  int<lower=1> samples;
  array[batches, samples] real y;
}

parameters {
  real theta;
  real<lower=0> tau_btw;
  real<lower=0> tau_with;
  array[batches] real mu;
}

model {
  theta ~ normal(0.0, 1.0 / sqrt(1.0E-10));
  tau_btw ~ gamma(0.001, 0.001);
  tau_with ~ gamma(0.001, 0.001);
  mu ~ normal(theta, 1.0 / sqrt(tau_btw));
  for (i in 1:batches) {
    for (j in 1:samples) {
      y[i,j] ~ normal(mu[i], 1.0 / sqrt(tau_with));
    }
  }
}

generated quantities {
  real sigma2_btw;
  real sigma2_with;
  sigma2_btw = 1 / tau_btw;
  sigma2_with = 1 / tau_with;
}
"""

data = json.loads("""
{
  "batches": 6,
  "samples": 5,
  "y": [
    [
      1545,
      1440,
      1440,
      1520,
      1580
    ],
    [
      1540,
      1555,
      1490,
      1560,
      1495
    ],
    [
      1595,
      1550,
      1605,
      1510,
      1560
    ],
    [
      1445,
      1440,
      1595,
      1465,
      1545
    ],
    [
      1595,
      1630,
      1515,
      1635,
      1625
    ],
    [
      1520,
      1455,
      1450,
      1480,
      1445
    ]
  ]
}
""")

inits = json.loads("""
{
  "theta": 1500,
  "tau_with": 1,
  "tau_btw": 1
}
""")

model_dir = os.path.join(os.path.dirname(__file__), "stan_model")
os.makedirs(model_dir, exist_ok=True)

model_file = os.path.join(model_dir, "model.stan")
with open(model_file, "w") as f:
    f.write(model_code)

data_file = os.path.join(model_dir, "data.json")
with open(data_file, "w") as f:
    json.dump(data, f)

inits_file = os.path.join(model_dir, "inits.json")
with open(inits_file, "w") as f:
    json.dump(inits, f)

model = cmdstanpy.CmdStanModel(stan_file=model_file)
fit = model.sample(
    data=data_file,
    inits=inits_file,
    chains=4,
    iter_warmup=1000,
    iter_sampling=1000,
    seed=42,
)

print(fit.summary())
print(fit.diagnose())
