#!/usr/bin/env python3
"""
Stan model generated by DoodleBUGS
Run with CmdStanPy: pip install cmdstanpy
"""
import json
import os
import cmdstanpy

model_code = """
data {
  int<lower=1> N;
  array[N] real x1;
  array[N] real x2;
  array[N] int n;
  array[N] int r;
}

parameters {
  real alpha0;
  real alpha1;
  real alpha2;
  real alpha12;
  real<lower=0> tau;
  array[N] real b;
}

transformed parameters {
  array[N] real p;
  for (i in 1:N) {
    p[i] = inv_logit(alpha0 + alpha1 * x1[i] + alpha2 * x2[i] + alpha12 * x1[i] * x2[i] + b[i]);
  }
}

model {
  alpha0 ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  alpha1 ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  alpha2 ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  alpha12 ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  tau ~ gamma(0.001, 0.001);
  b ~ normal(0.0, 1.0 / sqrt(tau));
  r ~ binomial(n, p);
}

generated quantities {
  real sigma;
  sigma = 1 / sqrt(tau);
}
"""

data = json.loads("""
{
  "r": [
    10,
    23,
    23,
    26,
    17,
    5,
    53,
    55,
    32,
    46,
    10,
    8,
    10,
    8,
    23,
    0,
    3,
    22,
    15,
    32,
    3
  ],
  "n": [
    39,
    62,
    81,
    51,
    39,
    6,
    74,
    72,
    51,
    79,
    13,
    16,
    30,
    28,
    45,
    4,
    12,
    41,
    30,
    51,
    7
  ],
  "x1": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
  ],
  "x2": [
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1
  ],
  "N": 21
}
""")

inits = json.loads("""
{
  "alpha0": 0,
  "alpha1": 0,
  "alpha2": 0,
  "alpha12": 0,
  "tau": 10
}
""")

model_dir = os.path.join(os.path.dirname(__file__), "stan_model")
os.makedirs(model_dir, exist_ok=True)

model_file = os.path.join(model_dir, "model.stan")
with open(model_file, "w") as f:
    f.write(model_code)

data_file = os.path.join(model_dir, "data.json")
with open(data_file, "w") as f:
    json.dump(data, f)

inits_file = os.path.join(model_dir, "inits.json")
with open(inits_file, "w") as f:
    json.dump(inits, f)

model = cmdstanpy.CmdStanModel(stan_file=model_file)
fit = model.sample(
    data=data_file,
    inits=inits_file,
    chains=4,
    iter_warmup=1000,
    iter_sampling=1000,
    seed=42,
)

print(fit.summary())
print(fit.diagnose())
