#!/usr/bin/env node
// Regenerates packages/cli/src/skill.generated.ts from packages/cli/skills.
// Embedded rather than shipped as loose files so the single-file binary can
// write the skill out too. Run via `pnpm gen:skill`; a test keeps them in sync.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "packages", "cli", "skills");
const out = join(root, "packages", "cli", "src", "skill.generated.ts");

/** Every file under skills/, keyed by its path relative to that directory. */
function walk(base) {
  const found = [];
  for (const name of readdirSync(base).sort()) {
    const full = join(base, name);
    if (statSync(full).isDirectory()) found.push(...walk(full));
    else found.push(full);
  }
  return found;
}

const entries = walk(dir)
  .map((path) => {
    const key = relative(dir, path).split(sep).join("/");
    return `  ${JSON.stringify(key)}: ${JSON.stringify(readFileSync(path, "utf8"))},`;
  })
  .join("\n");

writeFileSync(
  out,
  `// Generated by scripts/gen-skill.mjs from packages/cli/skills. Do not edit.
/** The agent skill, embedded so a compiled binary can install it. */
export const SKILL_FILES: Record<string, string> = {
${entries}
};
`,
);
process.stdout.write(`wrote ${out}\n`);
