#!/usr/bin/env python3
"""
Stan model generated by DoodleBUGS
Run with CmdStanPy: pip install cmdstanpy
"""
import json
import os
import cmdstanpy

model_code = """
data {
  int<lower=1> N;
  array[N] real t;
  array[N] int x;
}

parameters {
  real<lower=0> alpha;
  real<lower=0> beta;
  array[N] real<lower=0> theta;
}

transformed parameters {
  array[N] real lambda;
  for (i in 1:N) {
    lambda[i] = theta[i] * t[i];
  }
}

model {
  alpha ~ exponential(1);
  beta ~ gamma(0.1, 1.0);
  theta ~ gamma(alpha, beta);
  x ~ poisson(lambda);
}
"""

data = json.loads("""
{
  "t": [
    94.3,
    15.7,
    62.9,
    126,
    5.24,
    31.4,
    1.05,
    1.05,
    2.1,
    10.5
  ],
  "x": [
    5,
    1,
    5,
    14,
    3,
    19,
    1,
    1,
    4,
    22
  ],
  "N": 10
}
""")

inits = json.loads("""
{
  "alpha": 1,
  "beta": 1
}
""")

model_dir = os.path.join(os.path.dirname(__file__), "stan_model")
os.makedirs(model_dir, exist_ok=True)

model_file = os.path.join(model_dir, "model.stan")
with open(model_file, "w") as f:
    f.write(model_code)

data_file = os.path.join(model_dir, "data.json")
with open(data_file, "w") as f:
    json.dump(data, f)

inits_file = os.path.join(model_dir, "inits.json")
with open(inits_file, "w") as f:
    json.dump(inits, f)

model = cmdstanpy.CmdStanModel(stan_file=model_file)
fit = model.sample(
    data=data_file,
    inits=inits_file,
    chains=4,
    iter_warmup=1000,
    iter_sampling=1000,
    seed=42,
)

print(fit.summary())
print(fit.diagnose())
