#!/usr/bin/env python3
"""
Stan model generated by DoodleBUGS
Run with CmdStanPy: pip install cmdstanpy
"""
import json
import os
import cmdstanpy

model_code = """
data {
  int<lower=1> N;
  int<lower=1> T;
  array[N, T] int y;
  real log_Base4_bar;
  real Trt_bar;
  real BT_bar;
  real log_Age_bar;
  real V4_bar;
  array[N] real Base;
  array[N] real Trt;
  array[N] real Age;
  array[T] real V4;
}

parameters {
  real a0;
  real alpha_Base;
  real alpha_Trt;
  real alpha_BT;
  real alpha_Age;
  real alpha_V4;
  real<lower=0> tau_b1;
  real<lower=0> tau_b;
  array[N] real b1;
  array[N, T] real b;
}

transformed parameters {
  array[N, T] real mu;
  for (j in 1:N) {
    for (k in 1:T) {
      mu[j,k] = exp(a0 + alpha_Base * (log(Base[j] / 4) - log_Base4_bar) + alpha_Trt * (Trt[j] - Trt_bar) + alpha_BT * (Trt[j] * log(Base[j] / 4) - BT_bar) + alpha_Age * (log(Age[j]) - log_Age_bar) + alpha_V4 * (V4[k] - V4_bar) + b1[j] + b[j, k]);
    }
  }
}

model {
  a0 ~ normal(0.0, 1.0 / sqrt(1.0E-4));
  alpha_Base ~ normal(0.0, 1.0 / sqrt(1.0E-4));
  alpha_Trt ~ normal(0.0, 1.0 / sqrt(1.0E-4));
  alpha_BT ~ normal(0.0, 1.0 / sqrt(1.0E-4));
  alpha_Age ~ normal(0.0, 1.0 / sqrt(1.0E-4));
  alpha_V4 ~ normal(0.0, 1.0 / sqrt(1.0E-4));
  tau_b1 ~ gamma(1.0E-3, 1.0E-3);
  tau_b ~ gamma(1.0E-3, 1.0E-3);
  b1 ~ normal(0.0, 1.0 / sqrt(tau_b1));
  for (j in 1:N) {
    for (k in 1:T) {
      b[j,k] ~ normal(0.0, 1.0 / sqrt(tau_b));
      y[j,k] ~ poisson(mu[j, k]);
    }
  }
}

generated quantities {
  real alpha0;
  real sigma_b1;
  real sigma_b;
  alpha0 = a0 - alpha_Base * log_Base4_bar - alpha_Trt * Trt_bar - alpha_BT * BT_bar - alpha_Age * log_Age_bar - alpha_V4 * V4_bar;
  sigma_b1 = 1.0 / sqrt(tau_b1);
  sigma_b = 1.0 / sqrt(tau_b);
}
"""

data = json.loads("""
{
  "N": 59,
  "T": 4,
  "y": [
    [
      5,
      3,
      3,
      3
    ],
    [
      3,
      5,
      3,
      3
    ],
    [
      2,
      4,
      0,
      5
    ],
    [
      4,
      4,
      1,
      4
    ],
    [
      7,
      18,
      9,
      21
    ],
    [
      5,
      2,
      8,
      7
    ],
    [
      6,
      4,
      0,
      2
    ],
    [
      40,
      20,
      21,
      12
    ],
    [
      5,
      6,
      6,
      5
    ],
    [
      14,
      13,
      6,
      0
    ],
    [
      26,
      12,
      6,
      22
    ],
    [
      12,
      6,
      8,
      4
    ],
    [
      4,
      4,
      6,
      2
    ],
    [
      7,
      9,
      12,
      14
    ],
    [
      16,
      24,
      10,
      9
    ],
    [
      11,
      0,
      0,
      5
    ],
    [
      0,
      0,
      3,
      3
    ],
    [
      37,
      29,
      28,
      29
    ],
    [
      3,
      5,
      2,
      5
    ],
    [
      3,
      0,
      6,
      7
    ],
    [
      3,
      4,
      3,
      4
    ],
    [
      3,
      4,
      3,
      4
    ],
    [
      2,
      3,
      3,
      5
    ],
    [
      8,
      12,
      2,
      8
    ],
    [
      18,
      24,
      76,
      25
    ],
    [
      2,
      1,
      2,
      1
    ],
    [
      3,
      1,
      4,
      2
    ],
    [
      13,
      15,
      13,
      12
    ],
    [
      11,
      14,
      9,
      8
    ],
    [
      8,
      7,
      9,
      4
    ],
    [
      0,
      4,
      3,
      0
    ],
    [
      3,
      6,
      1,
      3
    ],
    [
      2,
      6,
      7,
      4
    ],
    [
      4,
      3,
      1,
      3
    ],
    [
      22,
      17,
      19,
      16
    ],
    [
      5,
      4,
      7,
      4
    ],
    [
      2,
      4,
      0,
      4
    ],
    [
      3,
      7,
      7,
      7
    ],
    [
      4,
      18,
      2,
      5
    ],
    [
      2,
      1,
      1,
      0
    ],
    [
      0,
      2,
      4,
      0
    ],
    [
      5,
      4,
      0,
      3
    ],
    [
      11,
      14,
      25,
      15
    ],
    [
      10,
      5,
      3,
      8
    ],
    [
      19,
      7,
      6,
      7
    ],
    [
      1,
      1,
      2,
      3
    ],
    [
      6,
      10,
      8,
      8
    ],
    [
      2,
      1,
      0,
      0
    ],
    [
      102,
      65,
      72,
      63
    ],
    [
      4,
      3,
      2,
      4
    ],
    [
      8,
      6,
      5,
      7
    ],
    [
      1,
      3,
      1,
      5
    ],
    [
      18,
      11,
      28,
      13
    ],
    [
      6,
      3,
      4,
      0
    ],
    [
      3,
      5,
      4,
      3
    ],
    [
      1,
      23,
      19,
      8
    ],
    [
      2,
      3,
      0,
      1
    ],
    [
      0,
      0,
      0,
      0
    ],
    [
      1,
      4,
      3,
      2
    ]
  ],
  "Trt": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
  ],
  "Base": [
    11,
    11,
    6,
    8,
    66,
    27,
    12,
    52,
    23,
    10,
    52,
    33,
    18,
    42,
    87,
    50,
    18,
    111,
    18,
    20,
    12,
    9,
    17,
    28,
    55,
    9,
    10,
    47,
    76,
    38,
    19,
    10,
    19,
    24,
    31,
    14,
    11,
    67,
    41,
    7,
    22,
    13,
    46,
    36,
    38,
    7,
    36,
    11,
    151,
    22,
    41,
    32,
    56,
    24,
    16,
    22,
    25,
    13,
    12
  ],
  "Age": [
    31,
    30,
    25,
    36,
    22,
    29,
    31,
    42,
    37,
    28,
    36,
    24,
    23,
    36,
    26,
    26,
    28,
    31,
    32,
    21,
    29,
    21,
    32,
    25,
    30,
    40,
    19,
    22,
    18,
    32,
    20,
    30,
    18,
    24,
    30,
    35,
    27,
    20,
    22,
    28,
    23,
    40,
    33,
    21,
    35,
    25,
    26,
    25,
    22,
    32,
    25,
    35,
    21,
    41,
    32,
    26,
    21,
    36,
    37
  ],
  "V4": [
    0,
    0,
    0,
    1
  ],
  "log_Base4_bar": 1.7679547,
  "log_Age_bar": 3.31978351,
  "Trt_bar": 0.52542373,
  "BT_bar": 0.94837775,
  "V4_bar": 0.25
}
""")

inits = json.loads("""
{
  "a0": 1,
  "alpha_Base": 0,
  "alpha_Trt": 0,
  "alpha_BT": 0,
  "alpha_Age": 0,
  "alpha_V4": 0,
  "tau_b1": 1,
  "tau_b": 1
}
""")

model_dir = os.path.join(os.path.dirname(__file__), "stan_model")
os.makedirs(model_dir, exist_ok=True)

model_file = os.path.join(model_dir, "model.stan")
with open(model_file, "w") as f:
    f.write(model_code)

data_file = os.path.join(model_dir, "data.json")
with open(data_file, "w") as f:
    json.dump(data, f)

inits_file = os.path.join(model_dir, "inits.json")
with open(inits_file, "w") as f:
    json.dump(inits, f)

model = cmdstanpy.CmdStanModel(stan_file=model_file)
fit = model.sample(
    data=data_file,
    inits=inits_file,
    chains=4,
    iter_warmup=1000,
    iter_sampling=1000,
    seed=42,
)

print(fit.summary())
print(fit.diagnose())
