#!/usr/bin/env python3
"""
Stan model generated by DoodleBUGS
Run with CmdStanPy: pip install cmdstanpy
"""
import json
import os
import cmdstanpy

model_code = """
data {
  int<lower=1> Num;
  array[Num] int nc;
  array[Num] int nt;
  array[Num] int rc;
  array[Num] int rt;
}

parameters {
  real d;
  real<lower=0> tau;
  array[Num] real mu;
  array[Num] real delta;
  real delta_new;
}

transformed parameters {
  array[Num] real pc;
  array[Num] real pt;
  for (i in 1:Num) {
    pc[i] = inv_logit(mu[i]);
    pt[i] = inv_logit(mu[i] + delta[i]);
  }
}

model {
  d ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  tau ~ gamma(0.001, 0.001);
  mu ~ normal(0.0, 1.0 / sqrt(1.0E-5));
  delta ~ normal(d, 1.0 / sqrt(tau));
  rc ~ binomial(nc, pc);
  rt ~ binomial(nt, pt);
  delta_new ~ normal(d, 1.0 / sqrt(tau));
}

generated quantities {
  real sigma;
  sigma = 1 / sqrt(tau);
}
"""

data = json.loads("""
{
  "rt": [
    3,
    7,
    5,
    102,
    28,
    4,
    98,
    60,
    25,
    138,
    64,
    45,
    9,
    57,
    25,
    33,
    28,
    8,
    6,
    32,
    27,
    22
  ],
  "nt": [
    38,
    114,
    69,
    1533,
    355,
    59,
    945,
    632,
    278,
    1916,
    873,
    263,
    291,
    858,
    154,
    207,
    251,
    151,
    174,
    209,
    391,
    680
  ],
  "rc": [
    3,
    14,
    11,
    127,
    27,
    6,
    152,
    48,
    37,
    188,
    52,
    47,
    16,
    45,
    31,
    38,
    12,
    6,
    3,
    40,
    43,
    39
  ],
  "nc": [
    39,
    116,
    93,
    1520,
    365,
    52,
    939,
    471,
    282,
    1921,
    583,
    266,
    293,
    883,
    147,
    213,
    122,
    154,
    134,
    218,
    364,
    674
  ],
  "Num": 22
}
""")

inits = json.loads("""
{
  "d": 0,
  "delta_new": 0,
  "tau": 1,
  "mu": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  "delta": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ]
}
""")

model_dir = os.path.join(os.path.dirname(__file__), "stan_model")
os.makedirs(model_dir, exist_ok=True)

model_file = os.path.join(model_dir, "model.stan")
with open(model_file, "w") as f:
    f.write(model_code)

data_file = os.path.join(model_dir, "data.json")
with open(data_file, "w") as f:
    json.dump(data, f)

inits_file = os.path.join(model_dir, "inits.json")
with open(inits_file, "w") as f:
    json.dump(inits, f)

model = cmdstanpy.CmdStanModel(stan_file=model_file)
fit = model.sample(
    data=data_file,
    inits=inits_file,
    chains=4,
    iter_warmup=1000,
    iter_sampling=1000,
    seed=42,
)

print(fit.summary())
print(fit.diagnose())
