// Regenerates src/html/uplot-assets.generated.ts from the installed uPlot package.
// Run `pnpm -F @mcmcjs/plots vendor:uplot` after bumping the uplot devDependency.
// The generated module inlines uPlot's MIT-licensed minified IIFE bundle and CSS as
// string constants so `buildHtmlDocument` can emit a fully self-contained HTML file.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const distDir = dirname(require.resolve("uplot/dist/uPlot.iife.min.js"));
const pkg = require("uplot/package.json");

const js = readFileSync(join(distDir, "uPlot.iife.min.js"), "utf8");
const css = readFileSync(join(distDir, "uPlot.min.css"), "utf8");

// JSON.stringify yields a fully-escaped JS string literal, safe regardless of any
// backticks, backslashes, or `${` sequences inside the minified bundle.
const out = `// @generated by scripts/vendor-uplot.mjs - do not edit by hand.
// uPlot ${pkg.version} (c) ${pkg.author?.name ?? "Leon Sorokin"}, MIT License.
// https://github.com/leeoniya/uPlot
/* biome-ignore-all lint: generated vendor bundle */

export const UPLOT_VERSION = ${JSON.stringify(pkg.version)};

export const UPLOT_JS = ${JSON.stringify(js)};

export const UPLOT_CSS = ${JSON.stringify(css)};
`;

const target = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "html",
  "uplot-assets.generated.ts",
);
writeFileSync(target, out);
console.log(`wrote ${target} (uPlot ${pkg.version}, js ${js.length}B, css ${css.length}B)`);
